Using different retry mechanism for curl I/O

diff --git a/client/bin/databridge-agent b/client/bin/databridge-agent
--- a/client/bin/databridge-agent
+++ b/client/bin/databridge-agent
@@ -186,11 +186,12 @@ function curl_io {
     local RET=0
     local ERROR_MSG=""
     local WHITESPACE="[[:space:]]"
+    local RETRIES=${IO_RETRIES}
     shift; shift
 
     # Extra args
     local CMDLINE="curl -k -u \"${AUTH_USER}:${AUTH_PASSWORD}\""
-    CMDLINE="${CMDLINE} -f -s -S -L --retry ${IO_RETRIES} --retry-delay ${IO_RETRY_DELAY} -X ${VERB}"
+    CMDLINE="${CMDLINE} -f -s -S -L -X ${VERB}"
     for (( i = 1; i <= $# ; i++ )); do
         eval ARG=\$$i
         if [[ $ARG =~ $WHITESPACE ]]
@@ -202,15 +203,27 @@ function curl_io {
     done
     CMDLINE="${CMDLINE} \"${URL}\""
 
-    # Perform HTTP GET
-    log 0 "Executing $CMDLINE"
-    exec 3>&1
-    ERROR_MSG=$(eval $CMDLINE 2>&1 1>&3)
-    RET=$?
-    exec 3>&-
+    # Repeat command if it fails
+    while true; do
 
-    # Log Errors
-    [ $RET -ne 0 ] && log 3 "$ERROR_MSG"
+        # Perform HTTP GET
+        log 0 "Executing $CMDLINE"
+        exec 3>&1
+        ERROR_MSG=$(eval $CMDLINE 2>&1 1>&3)
+        RET=$?
+        exec 3>&-
+
+        # If this was an error, retry
+        if [[ $RET -ne 0 && $RETRIES -gt 0 ]]; then
+            let RETRIES--
+            log 3 "$ERROR_MSG"
+            log 1 "In ${IO_RETRY_DELAY} sec will retry a CURL ${VERB} to ${URL}"
+            sleep ${IO_RETRY_DELAY}
+        else
+            break
+        fi
+
+    done
 
     # Return exit code
     return $RET
