Switching to numerical log level in agent

diff --git a/client/bin/databridge-agent b/client/bin/databridge-agent
--- a/client/bin/databridge-agent
+++ b/client/bin/databridge-agent
@@ -30,12 +30,12 @@ shift; shift;
 [ ! -z "$1" ] && DB_URL="$1" && shift
 
 # Handle other command-line arguments
-DEBUG=0
+LOG_LEVEL=1
 for I in $@; do
     case $I in
         --debug)
             # Enable debug logging
-            DEBUG=1
+            LOG_LEVEL=0
             ;;
         *)
             echo "ERROR: Unknown argument '$I'" >&2
@@ -62,14 +62,26 @@ DUMBQ_METRICS_BIN=$(which dumbq-metrics)
 
 # Log helper
 function log {
-    # Echo log line with date
     local LEVEL=$1
+    local LEVEL_STR="DEBUG"
     shift
-    # Skip debug logs unless enabled
-    [[ "$LEVEL" == "DEBUG" && $DEBUG -eq 0 ]] && return
+
+    # Do not log levels lower than
+    # the ones specified
+    [ $LEVEL -lt $LOG_LEVEL ] && return
+
+    # Translate level to string
+    if [ $LEVEL -eq 1 ]; then
+        LEVEL_STR="INFO"
+    elif [ $LEVEL -eq 2 ]; then
+        LEVEL_STR="WARN"
+    elif [ $LEVEL -eq 3 ]; then
+        LEVEL_STR="ERROR"
+    fi
+
     # Process multiline buffers
     while read L; do
-        echo "[$(date '+%d/%m/%Y %H:%M:%S')] ${LEVEL}: $L" 1>&2
+        echo "[$(date '+%d/%m/%Y %H:%M:%S')] ${LEVEL_STR}: $L" 1>&2
     done <<< "$*"
 }
 
@@ -109,20 +121,20 @@ function davix_io {
             CMDLINE="davix-rm $CMDLINE \"${URL}\""
             ;;
         *)
-            log "ERROR" "Unhandled HTTP Verb '${VERB}'"
+            log 3 "Unhandled HTTP Verb '${VERB}'"
             return 200
             ;;
     esac
 
     # Perform HTTP GET (davix-get also issues 'HEAD')
-    log DEBUG "Executing $CMDLINE"
+    log 0 "Executing $CMDLINE"
     exec 3>&1
     ERROR_MSG=$(eval $CMDLINE 2>&1)
     RET=$?
     exec 3>&-
 
     # Log Errors
-    [ $RET -ne 0 ] && log "ERROR" "$ERROR_MSG"
+    [ $RET -ne 0 ] && log 3 "$ERROR_MSG"
 
     # Return exit code
     return $RET
@@ -139,7 +151,7 @@ function curl_io {
 
     # Extra args
     local CMDLINE="curl -k -u \"${AUTH_USER}:${AUTH_PASSWORD}\""
-    CMDLINE="${CMDLINE} -f -s -S -L --retry 2 --retry-delay 10 -X ${VERB}"
+    CMDLINE="${CMDLINE} -f -s -S -L --retry 3 --retry-delay 15 -X ${VERB}"
     for (( i = 1; i <= $# ; i++ )); do
         eval ARG=\$$i
         if [[ $ARG =~ $WHITESPACE ]]
@@ -152,14 +164,14 @@ function curl_io {
     CMDLINE="${CMDLINE} \"${URL}\""
 
     # Perform HTTP GET
-    log DEBUG "Executing $CMDLINE"
+    log 0 "Executing $CMDLINE"
     exec 3>&1
     ERROR_MSG=$(eval $CMDLINE 2>&1 1>&3)
     RET=$?
     exec 3>&-
 
     # Log Errors
-    [ $RET -ne 0 ] && log "ERROR" "$ERROR_MSG"
+    [ $RET -ne 0 ] && log 3 "$ERROR_MSG"
 
     # Return exit code
     return $RET
@@ -172,13 +184,13 @@ function get_jobfile {
     # Get a job ID from the queue
     NEXT_JOB_ID=$(curl_io GET "${DB_INPUT_QUEUE}" --header "userID: ${AUTH_USER}")
     if [ $? -ne 0 ]; then
-        log "ERROR" "Could not fetch next job ID from queue"
+        log 3 "Could not fetch next job ID from queue"
         return 1
     fi
 
     # If queue is empty, return
     if [ -z "$NEXT_JOB_ID" ]; then
-        log "WARN" "The job description got from the input queue is empty!"
+        log 2 "The job description got from the input queue is empty!"
         return 1
     fi
 
@@ -188,7 +200,7 @@ function get_jobfile {
 
     # If we got an error, return
     if [ $? -ne 0 ]; then
-        log "ERROR" "Could not download job contents from server"
+        log 3 "Could not download job contents from server"
         return 1
     fi
 
@@ -211,14 +223,14 @@ function upload_jobdir {
     UPLOAD_URL="${DB_OUTPUT_URL}/${JOB_ID}.tgz?userdata=${USER_DATA}"
     davix_io PUT "${UPLOAD_URL}" "${ARCHIVE_FILE}"
     if [ $? -ne 0 ]; then
-        log "ERROR" "Unable to upload job to ${UPLOAD_URL}"
+        log 3 "Unable to upload job to ${UPLOAD_URL}"
         return
     fi
 
     # Schedule the job to be picked-up by the output queue
     curl_io PUT "${DB_OUTPUT_QUEUE}" -F "userdata=${JOB_ID}" --header "userID: ${AUTH_USER}"
     if [ $? -ne 0 ]; then
-        log "ERROR" "Unable to upload job description to ${DB_OUTPUT_QUEUE}"
+        log 3 "Unable to upload job description to ${DB_OUTPUT_QUEUE}"
         return
     fi
 
@@ -251,14 +263,14 @@ while true; do
     while [ -z "$JOB_ID" ]; do
 
         # Log attempts
-        log "INFO" "Fetching next job in queue"
+        log 1 "Fetching next job in queue"
 
         # Get next job file (updates JOB_ID)
         get_jobfile "${WORKDIR}"
 
         # Sleep on errors
         if [ $? -ne 0 ]; then
-            log "INFO" "Sleeping for 1 minute"
+            log 1 "Sleeping for 1 minute"
             sleep 60
         fi
 
@@ -272,7 +284,7 @@ while true; do
     [ ! -z "$DUMBQ_METRICS_BIN" ] && ${DUMBQ_METRICS_BIN} --set status=running
 
     # Run job
-    log "INFO" "Starting job ${JOB_ID}"
+    log 1 "Starting job ${JOB_ID}"
     ( cd "${WORKDIR}"; chmod +x job.sh; exec ./job.sh ) >${WORKDIR}/job.stdout 2>${WORKDIR}/job.stderr
 
     # Get exit code
@@ -283,11 +295,11 @@ while true; do
     let TS_DELTA=${TS_FINISHED}-${TS_STARTED}
 
     # Upload results
-    log "INFO" "Uploading results"
+    log 1 "Uploading results"
     upload_jobdir "${WORKDIR}" "${JOB_ID}" "exitcode=$EXIT_CODE&vmid=${DUMBQ_VMID}"
 
     # Cleanup
-    log "INFO" "Cleaning-up workdir"
+    log 1 "Cleaning-up workdir"
     rm -rf "${WORKDIR}"
 
     # Update DumbQ Metrics if existing
@@ -305,12 +317,12 @@ while true; do
     # Apply blackhole protection
     if [ $TS_DELTA -lt ${BHP_MIN_JOB_TIME} ]; then
         # The job is quitting faster than expected
-        log "WARN" "Black hole detected. Job exited after ${TS_DELTA} seconds (<${BHP_MIN_JOB_TIME})"
+        log 2 "Black hole detected. Job exited after ${TS_DELTA} seconds (<${BHP_MIN_JOB_TIME})"
         # Scale-up the blackhole timer delay
         let BHP_TIMER*=2
         # If we have exceeded BHP_MAX_DELAY, abort!
         if [ $BHP_TIMER -gt ${BHP_MAX_DELAY} ]; then
-            log "ERROR" "Exceeded BHP max timer, will reboot!"
+            log 3 "Exceeded BHP max timer, will reboot!"
             reboot
             exit 1
         fi
@@ -320,7 +332,7 @@ while true; do
     fi
 
     # Sleep a bit
-    log "INFO" "Sleeping for ${BHP_TIMER} seconds"
+    log 1 "Sleeping for ${BHP_TIMER} seconds"
     sleep ${BHP_TIMER}
 
 done
