Fixing command-line on client curl/davix

diff --git a/client/bin/davix-server-test b/client/bin/davix-server-test
--- a/client/bin/davix-server-test
+++ b/client/bin/davix-server-test
@@ -3,7 +3,7 @@
 # We will need the BOINC UserID and BOINC Authenticator as the first two parameters
 AUTH_USER="35331"
 AUTH_PASSWORD="4c2ce9458a4750eafd589c9b4269fc2b"
-DEBUG=1
+LOG_LEVEL=0
 
 # Define URLs using base URL as reference
 DB_URL="https://t4t-data-bridge.cern.ch"
@@ -14,14 +14,26 @@ DB_OUTPUT_URL="${DB_URL}/myfed/t4t-boinc/output"
 
 # Log helper
 function log {
-    # Echo log line with date
     local LEVEL=$1
+    local LEVEL_STR="DEBUG"
     shift
-    # Skip debug logs unless enabled
-    [[ "$LEVEL" == "DEBUG" && $DEBUG -eq 0 ]] && return
+
+    # Do not log levels lower than
+    # the ones specified
+    [ $LEVEL -lt $LOG_LEVEL ] && return
+
+    # Translate level to string
+    if [ $LEVEL -eq 1 ]; then
+        LEVEL_STR="INFO"
+    elif [ $LEVEL -eq 2 ]; then
+        LEVEL_STR="WARN"
+    elif [ $LEVEL -eq 3 ]; then
+        LEVEL_STR="ERROR"
+    fi
+
     # Process multiline buffers
     while read L; do
-        echo "[$(date '+%d/%m/%Y %H:%M:%S')] ${LEVEL}: $L" 1>&2
+        echo "[$(date '+%d/%m/%Y %H:%M:%S')] ${LEVEL_STR}: $L" 1>&2
     done <<< "$*"
 }
 
@@ -30,12 +42,13 @@ function davix_io {
     local VERB=$1
     local URL=$2
     local FILE=$3
-    local RET=0
+    local RET=256
     local ERROR_MSG=""
+    local RETRIES=3
     shift; shift; shift
 
     # Extra args
-    local CMDLINE="-k -k --userlogin \"${AUTH_USER}\" --userpass \"${AUTH_PASSWORD}\""
+    local CMDLINE="-k --userlogin \"${AUTH_USER}\" --userpass \"${AUTH_PASSWORD}\""
     for (( i = 1; i <= $# ; i++ )); do
         eval ARG=\$$i
         if [[ $ARG =~ $WHITESPACE ]]
@@ -49,34 +62,48 @@ function davix_io {
     # Handle verb accordint to case
     case $VERB in
         GET)
-            # Use davix-http for GET request
-            CMDLINE="davix-http -X GET $CMDLINE -o ${FILE} \"${URL}\""
+            # Use davix-get to download a file
+            CMDLINE="davix-get $CMDLINE \"${URL}\" ${FILE}"
             ;;
         PUT)
-            # Use davix-http for GET request
+            # Use davix-put to upload a file
             CMDLINE="davix-put $CMDLINE ${FILE} \"${URL}\""
             ;;
         DELETE)
-            # Use davix-http for GET request
+            # Use davix-rm to delete a file
             CMDLINE="davix-rm $CMDLINE \"${URL}\""
             ;;
         *)
-            log "ERROR" "Unhandled HTTP Verb '${VERB}'"
+            log 3 "Unhandled DAVIX Verb '${VERB}'"
             return 200
             ;;
     esac
 
-    # Perform HTTP GET (davix-get also issues 'HEAD')
-    log DEBUG "Executing $CMDLINE"
-    exec 3>&1
-    ERROR_MSG=$(eval $CMDLINE 2>&1)
-    RET=$?
-    exec 3>&-
+    # Repeat command if it fails
+    while true; do
 
-    log DEBUG "davix returned $RET"
+        # Perform DAVOX I/O
+        log 0 "Executing $CMDLINE"
+        exec 3>&1
+        ERROR_MSG=$(eval $CMDLINE 2>&1)
+        RET=$?
+        exec 3>&-
+        log 0 "Exited with $RET"
 
-    # Log Errors
-    [ $RET -ne 0 ] && log "ERROR" "$ERROR_MSG"
+        # If this was an error, retry
+        if [[ $RET -ne 0 && $RETRIES -gt 0 ]]; then
+            let RETRIES--
+            log 3 "$ERROR_MSG"
+            log 1 "In 10 sec will retry a DAVIX ${VERB} to ${URL}"
+            sleep 10
+        else
+            break
+        fi
+
+    done
+
+    # Log errors
+    [ $RET -ne 0 ] && log 3 "$ERROR_MSG"
 
     # Return exit code
     return $RET
@@ -93,7 +120,7 @@ function curl_io {
 
     # Extra args
     local CMDLINE="curl -k -u \"${AUTH_USER}:${AUTH_PASSWORD}\""
-    CMDLINE="${CMDLINE} -f -s -S -L --retry 2 --retry-delay 10 -X ${VERB}"
+    CMDLINE="${CMDLINE} -f -s -S -L --retry 3 --retry-delay 10 -X ${VERB}"
     for (( i = 1; i <= $# ; i++ )); do
         eval ARG=\$$i
         if [[ $ARG =~ $WHITESPACE ]]
@@ -106,16 +133,14 @@ function curl_io {
     CMDLINE="${CMDLINE} \"${URL}\""
 
     # Perform HTTP GET
-    log DEBUG "Executing $CMDLINE"
+    log 0 "Executing $CMDLINE"
     exec 3>&1
     ERROR_MSG=$(eval $CMDLINE 2>&1 1>&3)
     RET=$?
     exec 3>&-
 
-    log DEBUG "curl returned $RET"
-
-    # Log Errors
-    [ $RET -ne 0 ] && log "ERROR" "$ERROR_MSG"
+    # Log 3s
+    [ $RET -ne 0 ] && log 3 "$ERROR_MSG"
 
     # Return exit code
     return $RET
@@ -136,30 +161,30 @@ while [ $I -lt 100 ]; do
     let I++
     UUID=$(uuidgen)
     URL="${DB_OUTPUT_URL}/test-${UUID}.tar.gz"
-    log INFO "Test #$I, delay $I, ($UUID)"
+    log 1 "Test #$I, delay $I, ($UUID)"
 
     # Upload the blob
     davix_io PUT "${URL}" blob
-    [ $? -ne 0 ] && log ERROR "Unable to upload to ${URL}" && continue
+    [ $? -ne 0 ] && log 3 "Unable to upload to ${URL}" && continue
 
     # Wait for a while
-    log INFO "Delaying for $I sec"
+    log 1 "Delaying for $I sec"
     sleep $I
 
     # Download the blob
     davix_io GET "${URL}" inblob
-    [ $? -ne 0 ] && log ERROR "Unable to download from ${URL}"
+    [ $? -ne 0 ] && log 3 "Unable to download from ${URL}"
 
     # Delete the blob
     davix_io DELETE "${URL}" inblob
-    [ $? -ne 0 ] && log ERROR "Unable to delete url ${URL}" && continue
+    [ $? -ne 0 ] && log 3 "Unable to delete url ${URL}" && continue
 
     # Check hash
     CHECK_HASH=$(shasum -a1 inblob | awk '{print $1}')
     if [ "$CHECK_HASH" != "$VALID_HASH" ]; then
-        log ERROR "!!!! Hash mismatch between download and upload"
+        log 3 "!!!! Hash mismatch between download and upload"
     else
-        log INFO "++++ Hash matches, I/O successful after $I sec delay"
+        log 1 "++++ Hash matches, I/O successful after $I sec delay"
     fi
 
 done
