Adding better error handling

diff --git a/server/bin/databridge-server-sync b/server/bin/databridge-server-sync
--- a/server/bin/databridge-server-sync
+++ b/server/bin/databridge-server-sync
@@ -86,17 +86,25 @@ function get_outfile {
 
 		# Create directory
 		mkdir -p "${JOB_OUTPUT_DIR}"
+		[ $? -ne 0 ] && echo "ERROR: Could not create directory ${JOB_OUTPUT_DIR}" && return 1
 
 		# Change owner if reuqired
-		[ ! -z "${DATABRIDGE_OUTPUT_OWNER}" ] && chown ${DATABRIDGE_OUTPUT_OWNER} "${JOB_OUTPUT_DIR}"
+		if [ ! -z "${DATABRIDGE_OUTPUT_OWNER}" ]; then
+			chown ${DATABRIDGE_OUTPUT_OWNER} "${JOB_OUTPUT_DIR}"
+			[ $? -ne 0 ] && echo "ERROR: Could not change ownership of ${JOB_OUTPUT_DIR}" && return 1
+		fi
 
 	fi
 
 	# Move file to the proper location
 	mv "${F_JOB}" "${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz"
+	[ $? -ne 0 ] && echo "ERROR: Could not move job file to ${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz" && return 1
 
 	# Change owner if reuqired
-	[ ! -z "${DATABRIDGE_OUTPUT_OWNER}" ] && chown ${DATABRIDGE_OUTPUT_OWNER} "${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz"
+	if [ ! -z "${DATABRIDGE_OUTPUT_OWNER}" ]; then
+		chown ${DATABRIDGE_OUTPUT_OWNER} "${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz"
+		[ $? -ne 0 ] && echo "ERROR: Could not change ownership of ${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz" && return 1
+	fi
 
 	# Everything worked as expected, delete output (cleanup)
 	curl -f -X DELETE --key ${DATABRIDGE_SSL_KEY} --cert ${DATABRIDGE_SSL_CERT} -k -L -s "${DATABRIDGE_OUTPUT_URL}/${JOB_ID}.tgz"
