Moving callbacks to function scope

diff --git a/server/bin/databridge-server-sync b/server/bin/databridge-server-sync
--- a/server/bin/databridge-server-sync
+++ b/server/bin/databridge-server-sync
@@ -72,6 +72,19 @@ function put_jobfile {
 	log 1 "Job ${JOB_ID} placed in queue"
 	echo "$JOB_ID:$(date +%s)" >> $DATABRIDGE_JOB_LIST
 
+	# Fire appropriate callback
+	if [ ! -z "${DATABRIDGE_CB_SCHEDULED}" ]; then
+		# Fire callback
+		${DATABRIDGE_CB_SCHEDULED} "${FILE}" "${JOB_ID}"
+		ANS=$?
+		# Check result
+		if [ $? -ne 0 ]; then
+			log 2 "SCHEDULED callback failed (exit code $ANS)"
+		else
+			log 1 "SCHEDULED callback executed successfully"
+		fi
+	fi
+
 	# Return 0
 	return 0
 }
@@ -133,6 +146,19 @@ function get_outfile {
 	curl -f -X DELETE --key ${DATABRIDGE_SSL_KEY} --cert ${DATABRIDGE_SSL_CERT} -k -L -s "${DATABRIDGE_OUTPUT_URL}/${JOB_ID}.tgz"
 	[ $? -ne 0 ] && log 2 "Unable to clean job output of job ${JOB_ID}"
 
+	# Fire appropriate callback
+	if [ ! -z "${DATABRIDGE_CB_COMPLETED}" ]; then
+		# Fire callback
+		${DATABRIDGE_CB_COMPLETED} "${JOB_OUTFILE}" "${JOB_ID}"
+		ANS=$?
+		# Check result
+		if [ $? -ne 0 ]; then
+			log 2 "COMPLETED callback failed (exit code $ANS)"
+		else
+			log 1 "COMPLETED callback executed successfully"
+		fi
+	fi
+
 	# Return 0
 	return 0
 }
@@ -168,19 +194,6 @@ function upload_jobs {
 
 		# Upon successful placement, remove
 		if [ $? -eq 0 ]; then
-
-			# Fire appropriate callback
-			if [ ! -z "${DATABRIDGE_CB_SCHEDULED}" ]; then
-				# Fire callback
-				${DATABRIDGE_CB_SCHEDULED} "${FILE}" "${JOB_ID}"
-				ANS=$?
-				# Check result
-				if [ $? -ne 0 ]; then
-					log 2 "SCHEDULED callback failed (exit code $ANS)"
-				else
-					log 1 "SCHEDULED callback executed successfully"
-				fi
-			fi
 
 			# Delete file
 			rm $FILE
@@ -349,19 +362,6 @@ function download_jobs_sequential {
 
 			# Job downloaded
 			log 1 "Job ${JOB_ID} completed"
-
-			# Fire appropriate callback
-			if [ ! -z "${DATABRIDGE_CB_COMPLETED}" ]; then
-				# Fire callback
-				${DATABRIDGE_CB_COMPLETED} "${JOB_OUTFILE}" "${JOB_ID}"
-				ANS=$?
-				# Check result
-				if [ $? -ne 0 ]; then
-					log 2 "COMPLETED callback failed (exit code $ANS)"
-				else
-					log 1 "COMPLETED callback executed successfully"
-				fi
-			fi
 
 			# Reset stale counter
 			STALE_COUNTER=0
