Adding configurable extension

diff --git a/server/bin/databridge-server-sync b/server/bin/databridge-server-sync
--- a/server/bin/databridge-server-sync
+++ b/server/bin/databridge-server-sync
@@ -63,7 +63,7 @@ function get_outfile {
 	local JOB_OUTPUT_DIR=""
 
 	# Temporary files
-	F_JOB="${TMP_DIR}/jobout.tar.gz"
+	F_JOB="${TMP_DIR}/jobout${DATABRIDGE_OUTPUT_EXT}"
 	F_HEADERS="${TMP_DIR}/headers.txt"
 
 	# Try to get job file from output directory into the temporary files
@@ -97,13 +97,13 @@ function get_outfile {
 	fi
 
 	# Move file to the proper location
-	mv "${F_JOB}" "${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz" 2>/dev/null
-	[ $? -ne 0 ] && echo "ERROR: Could not move job file to ${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz" && return 1
+	mv "${F_JOB}" "${JOB_OUTPUT_DIR}/${JOB_ID}${DATABRIDGE_OUTPUT_EXT}" 2>/dev/null
+	[ $? -ne 0 ] && echo "ERROR: Could not move job file to ${JOB_OUTPUT_DIR}/${JOB_ID}${DATABRIDGE_OUTPUT_EXT}" && return 1
 
 	# Change owner if reuqired
 	if [ ! -z "${DATABRIDGE_OUTPUT_OWNER}" ]; then
-		chown ${DATABRIDGE_OUTPUT_OWNER} "${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz" 2>/dev/null
-		[ $? -ne 0 ] && echo "WARNING: Could not change ownership of ${JOB_OUTPUT_DIR}/${JOB_ID}.tar.gz"
+		chown ${DATABRIDGE_OUTPUT_OWNER} "${JOB_OUTPUT_DIR}/${JOB_ID}${DATABRIDGE_OUTPUT_EXT}" 2>/dev/null
+		[ $? -ne 0 ] && echo "WARNING: Could not change ownership of ${JOB_OUTPUT_DIR}/${JOB_ID}${DATABRIDGE_OUTPUT_EXT}"
 	fi
 
 	# Everything worked as expected, delete output (cleanup)
