Re-scheduling expired jobs

diff --git a/server/bin/databridge-server-sync b/server/bin/databridge-server-sync
--- a/server/bin/databridge-server-sync
+++ b/server/bin/databridge-server-sync
@@ -411,18 +411,44 @@ function download_jobs_fifo {
 					# Warn the user, and don't touch stale counter
 					log 2 "Job ${JOB_ID} expired after ${DELTA} seconds"
 
-					# Fire appropriate callback
-					if [ ! -z "${DATABRIDGE_CB_EXPIRED}" ]; then
-						# Fire callback
-						${DATABRIDGE_CB_EXPIRED} "${JOB_ID}"
-						ANS=$?
-						# Check result
-						if [ $? -ne 0 ]; then
-							log 2 "EXPIRED callback failed (exit code $ANS)"
-						else
-							log 1 "EXPIRED callback executed successfully"
+					# Check if we should not re-schedule
+					if [ ${DATABRIDGE_EXPIRE_RESCHEDULE} -eq 0 ]; then
+
+						# Fire appropriate callback
+						if [ ! -z "${DATABRIDGE_CB_EXPIRED}" ]; then
+							# Fire callback
+							${DATABRIDGE_CB_EXPIRED} "${JOB_ID}"
+							ANS=$?
+							# Check result
+							if [ $? -ne 0 ]; then
+								log 2 "EXPIRED callback failed (exit code $ANS)"
+							else
+								log 1 "EXPIRED callback executed successfully"
+							fi
 						fi
+
+						# Delete input files
+						davix_io DELETE "${DATABRIDGE_INPUT_URL}/${JOB_ID}"
+						[ $? -ne 0 ] && log 3 "Unable to delete input file: ${DATABRIDGE_INPUT_URL}/${JOB_ID}"
+
+					# Otherwise re-schedule
+					else
+
+						# Upload job ID on FIFO	
+						log 1 "Putting job ${JOB_ID} description back in queue"
+						curl_io PUT "${DATABRIDGE_QUEUE_URL}" -F "userdata=${JOB_ID}" --header "jobID: ${JOB_ID}"
+						if [ $? -ne 0 ]; then
+							# Remove from queue
+							log 3 "Could not upload job description, removing job file"
+							davix_io DELETE "${DATABRIDGE_INPUT_URL}/${JOB_ID}"
+							[ $? -ne 0 ] && log 3 "Unable to delete input file: ${DATABRIDGE_INPUT_URL}/${JOB_ID}"
+						else
+							# Re-schedule job
+							echo "$JOB_ID:$(date +%s)" >> ${ROTATE_FILE}	
+						fi
+
 					fi
+
 
 				else
 					# Otherwise process later
@@ -652,6 +678,7 @@ fi
 
 # Set some defaults
 [ -z "${DATABRIDGE_JOB_TIMEOUT}" ] && DATABRIDGE_JOB_TIMEOUT=0
+[ -z "${DATABRIDGE_EXPIRE_RESCHEDULE}" ] && DATABRIDGE_EXPIRE_RESCHEDULE=1
 
 # Override log level from the command line
 for L in $@; do
